### PR TITLE
Added Support badge

### PR DESCRIPTION
**Pull request by OrKoN**
Hi @bevacqua,

this PR adds another badge for accepting donations. It's more friendly for one-time donations but supports recurring donations as well (and it's free). So it may work better than the other two badges. If you like the badge, you should sign in to the service website using your Github account and enter your PayPal address there to start accepting donations. It's also possible to change the goals and the description of the project. Our badge is also used by other open source projects, for example, JSPM and WDRL. 

If you don't like the idea of having an extra badge, please close this PR and I will remove the project page from our website.

Best regards and thanks for great open source projects,

Alex
co-creator of supporter.60devs.com

### CODE REVIEW

**Comment by bevacqua** [comment]
I guess it can't hurt, these badges rarely do anything worthwhile tho

**Comment by OrKoN** [comment]
Great! Let me know if you have problems signing in and specifying the PayPal email address.

**Comment by OrKoN** [comment]
Btw, we've got some good results for JSPM this month: https://supporter.60devs.com/support/33df4abbec4d39260f49015d2457eafe/JSPM But community of this project is very strong.

**Comment by bevacqua** [comment]
Interesting. I've added the buy me a cup of coffee thing to `dragula` which is far more popular than this.

**Pull request merged**
